services:
  nginx:
    container_name: nginx
    build: .
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/www/html:/var/www/html
      - ./nginx/logs:/var/log/nginx
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/certs:/etc/nginx/certs:ro
    restart: unless-stopped
    networks:
      - backend

  postgres:
    depends_on:
      - nginx
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
    volumes:
      - ../volumes/postgres:/var/lib/postgresql/data
    restart: unless-stopped
    ports:
      - 5432:5432
    networks:
      - backend

  pgadmin:
    depends_on:
      - nginx
      - postgres
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    restart: unless-stopped
    ports:
      - 5050:80
    networks:
      - backend

  # redis:
  #   depends_on:
  #     - nginx
  #   container_name: redis
  #   image: redis:latest
  #   restart: unless-stopped
  #   ports:
  #     - 6379:6379
  #   networks:
  #     - backend

networks:
  backend:
    driver: bridge
