name: Docker Compose Deploy

on:
  push:
    branches: ["release"]
  pull_request:
    branches: ["release"]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check if Docker is installed
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            if ! command -v docker &> /dev/null; then
              echo "Docker is not installed. Installing..."
              sudo curl -fsSL https://get.docker.com | sh
            else
              echo "Docker is already installed."
            fi
