name: Deploy master to server

env:
  MASTER_DIR: app/master

on:
  push:
    branches: ["release"]
  pull_request:
    branches: ["release"]

jobs:
  check:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check if Docker is installed
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            if ! command -v docker &> /dev/null; then
              echo "Docker is not installed. Installing..."
              sudo curl -fsSL https://get.docker.com | sh
            else
              echo "Docker is already installed."
            fi

  deploy:
    runs-on: ubuntu-latest
    needs: check

    steps:
      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            if [ -d "${{ env.MASTER_DIR }}/.git" ]; then
              echo "Found repository. Pulling..."
              git pull origin release
              echo "Repository is updated."
            else
              echo "Repository is not pulled. Pulling..."
              git clone ${{ github.repositoryUrl }} -b release --single-branch ${{ env.MASTER_DIR }}
              echo "Repository is pulled."
            fi

      - name: Run Docker Compose
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd ${{ env.MASTER_DIR }}
            if [ -f "docker-compose.yml" ]; then
              if [ ! -f ".env" ]; then
                touch .env
              fi
              sudo docker compose down --remove-orphans
              sudo docker compose up -d --build
            fi